### ISSUE TITLE
The sequence ckCR is added to the buffer if a macro has CR and latex_to_unicode_auto = true

### ISSUE THREAD

**Issue by ronisbr** [JuliaEditorSupport/julia-vim#256]
Hi!

I am having a strange bug using Neovim `master`, this plugin, and the option `latex_to_unicode_auto = true`. In this configuration, if a hit `<CR>` inside a macro, when it exits it adds the sequence `ckCR` in the buffer.

**Configuration before executing the macro**

<img width="790" alt="Captura de Tela 2021-04-23 às 11 00 06" src="https://user-images.githubusercontent.com/1068295/115882361-118a0280-a423-11eb-8ca7-efb694704cd8.png">

The macro is recorded by: `qqA<CR>q`

**Configuration after executing the macro in the 2nd line**

<img width="790" alt="Captura de Tela 2021-04-23 às 11 00 51" src="https://user-images.githubusercontent.com/1068295/115882482-2bc3e080-a423-11eb-8c04-1d85dae64ede.png">

This problem does not happen with `latex_to_unicode_auto = false`.

**Comment by carlobaldassi** [comment]
Thanks, I can confirm the issue, even with older vim versions.
The origin of this is in the fact that when Vim executes a macro, mappings do not work in the same way as when typing. You can see what's actually being executed by pasting in the file what's on register `q`, with `"qp`. Inside there there is the trigger for the fallback behavior of `<CR>`. This is what I get after reqcording `A<CR><Esc>`:
```
A^M<91>L2UFallbackCR^[
```
The part `<91>L2UFallbackCR` should trigger a mapping that actually inputs the `<CR>` character (and indeed it does, when typing). This can be seen with the command `:imap <buffer>`. However it doesn't work in a macro. I'm not sure why and it's not documented.

The solution would be to find a mapping that works and doesn't run the risk of overwriting other existing mappings, but it's not trivial. As I said, the documentation doesn't mention anything like this and I tried a few alternatives, mostly unsuccessfully.

I also can't find any way to detect whether we're recording a macro (at least in that case we might disable L2U altogether).

This issue also affects the `<Tab>` mapping, and may also come up when auto-sub of a LaTeX sequence is triggered by hitting the Return key.

I'll keep trying to fix this, but any ideas are welcome...

**Comment by carlobaldassi** [comment]
By the way this is where the trigger is defined: https://github.com/JuliaEditorSupport/julia-vim/blob/d0bb06ffc40ff7c49dfa2548e007e9013eaeabb7/autoload/LaTeXtoUnicode.vim#L70

The other triggers are in nearby lines.

**Comment by ronisbr** [comment]
Thanks @carlobaldassi for the information! I will try to help (but my knowledge is not that deep in this area :) )

**Comment by ronisbr** [comment]
I see what you said. I could make it work by using `feedchar("\n", 't')`, however this will not work generally. Did you consider opening a bug in Vim / Neovim? I did not have the technical knowledge to do that myself.

**Comment by carlobaldassi** [comment]
I think I figured it out. For me it's fixed now, let me know if there are still issues, corner cases, etc.

**Comment by ronisbr** [comment]
Awesome @carlobaldassi ! Thank you very much. This fixed the problem here also.

**Comment by ronisbr** [comment]
By the way, just for your information, we still have problem with `TAB`, as you mentioned. However, I hardly hit TAB during macro recordings :)
