### ISSUE TITLE
`ij` text object selects part of multi-line signature

### ISSUE THREAD

**Issue by nick4f42** [JuliaEditorSupport/julia-vim#286]
The `ij` text object includes some of the signature if it spans multiple lines:

![julia-vim-ij](https://user-images.githubusercontent.com/51063625/156664090-e79a6f99-aa6a-4774-90c6-6dc8e6dde9d6.gif)

**Comment by carlobaldassi** [comment]
I have just pushed a fix for the issue in the first example. Unfortunately, fixing the one-line blocks and other cases is very, very hard. That's because that basically requires a full-fledged julia code parser.
Examples of things that still create problems after the fix:
1. Lines that continue due to a dangling operator, e.g.
    ```
    if x + y ==
       z + k
        println("yes")
    end
    ```
2. Code that comes in the same line after the block header, e.g.
    ```
    if x == z + k println("yes")
        return
    end
    ```

In order to deal with those correctly, we'd need a parser that can tell when an expression is completed. Doing it with brackets is not too hard, but when the tokens that determine the parsing are in the middle (like for binary operators) and there is whitespace dependency (e.g. `a [3]` is not the same as `a[3]` in this context) then things become very complicated to implement in vim script. It might be doable by leveraging syntax highlighting (as we do with brackets) but that would likely make the syntax highlighting even more horribly slow than it is already.

**Comment by nick4f42** [comment]
Thanks for the quick fix! For completeness, I'll give another example I found that still doesn't work:

3. When the `where` statement of a function is on a different line, it's included in `ij`
```jl
function f(
        x::T
    ) where T
    return T
end
```
